apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springboot
  namespace: spring-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
