apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: spring-app
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: spring-app
spec:
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/springboot-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
